name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: apt update && apt install -y bash g++ make mosquitto-dev curl-dev && apt-get clean && rm -rf /var/lib/apt/lists/*
    - name: make
      run: make WITH_INFLUXDB=no
